import { Geist, Geist_Mono } from "next/font/google"; //Overvej at bruge dine egne fonte her
import "./globals.css"; //Muligheden for at bruge et traditionelt CSS stylesheet

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: /* "Create Next App" */ "Mit projekt", //Titel på fanen (Ligesom title tag i HTML)
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children /* Ligesom slot i Astro */}
      </body>
    </html>
  );
}
